### ISSUE TITLE
Send user query with spaces instead of +

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#122]
frontend sends user queries in the format:
"query=word1+word2+word3", better would be "query=word1 word2 word3"

**Comment by oliviadargel** [comment]
Please inform backend if this task is done

**Comment by weribell** [comment]
The frontend submits the query encoded according to the `application/x-www-form-urlencoded` specification, which enforces this kind of encoding, where spaces are automatically replaced using the "+" sign. So to implement this we would have to switch to a different format. Please see [my other comment](https://github.com/amosproj/amos2021ws01-geo-data-search/issues/123#issuecomment-984377974) for more info.

**Comment by oliviadargel** [comment]
solved in Backend at [commit bdf4b3ecb933ea02a0665ec56ac458b099278d6e](https://github.com/amosproj/amos2021ws01-geo-data-search/commit/bdf4b3ecb933ea02a0665ec56ac458b099278d6e)
