### ISSUE TITLE
rm "query=" from user query (if possible)

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#123]
user query has format:
"query=Hamburg", better would be just "Hamburg"

**Comment by oliviadargel** [comment]
Please inform backend if this task is done

**Comment by weribell** [comment]
I don't think this is technically possible, as long as we use the `application/x-www-form-urlencoded` format. The frontend sends the search query encoded using the `application/x-www-form-urlencoded` format, you can read more about it [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST). I have implemented it like this, after discussing the details with NIkita during initial implementation. According to its specification, each value must have a key. So the search term submitted in the search request has to have a key, in this case - query. It should be easy to parse on the server using a middleware. 

So, it would be theoretically possible to send the query as is (without query= as you request), if I switch from `application/x-www-form-urlencoded` and send the query in plain text format.

**Comment by oliviadargel** [comment]
Backend removes "query="
