### ISSUE TITLE
docker (re)build should run 30 seconds MAX

### ISSUE THREAD

**Issue by Decappi** [amosproj/amos2021ws01-geo-data-search#139]
## User story
1. As a developer
2. I want a snappy docker build process, the build process should only take long if it's the first time
3. So that I can have fast feedback loops in my development process

## Acceptance criteria
* docker compose up --build takes no more than 20 seconds
* all permanent changes to the container happen before the container is started

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by oliviadargel** [comment]
That will be impossible in case no model is trained locally as the training is then called on container start up
