### ISSUE TITLE
External APIs: Feature research

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#151]
## User story
1. As a backend developer
2. I want to research for features that OSM/Here API have
3. So that I can integrate the most important features into the Backend component

## Acceptance criteria
* possible features are listed
* focus on routing
* possible features were discussed within the group
* the result of the discussion is written down in issues (see #152  as example)

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by Decappi** [comment]
2021-12-14
External API research
- OSM
	- Bounding box for the results
	- [Tile service](http://project-osrm.org/docs/v5.5.1/api/#tile-service):
		- Returns all vector tiles in a given square, allowing to gather info road sections
			- name of the road
			- speed
			- bearing
			- turn_angle
	- [Overpass API](https://wiki.openstreetmap.org/wiki/Overpass_API)
		- query for features like
			- street surface
			- sidewalk
			- maxspeed
			- lit (lighting conditions)
			- road type
				- highway
				- cycleway
				- footway
				- sidewalk
				- winter road
			- road signs like
				- overtaking
				- parking
				- priority road
			- amenity
				- charging station
				- bar 
				- biergarten
				- restaurant
				- toilets
			- barrier
				- toll_booth
				- toll_gantry
	- [Openrouteservice](openrouteservice.org)
		- Allows for navigation and excluding toll roads
	- Graphhopper
		- [Charging stations along the route](https://www.graphhopper.com/blog/2015/05/05/solving-the-electric-vehicle-charging-problematic-fast-with-graphhopper/)

**Comment by Decappi** [comment]
- HERE
	- Vector Tile API
		- roads layer
			- toll
			- fclass with motorway etc
tbc
