### ISSUE TITLE
Toll roads

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#152]
## User story
1. As a user 
2. I want to be able to decide whether I want to allow toll roads or not
3. So that I don't have to pay tolls if I don't want to

## Acceptance criteria
* Request to external API is sent with request for toll free roads

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by NumanFidan** [comment]
`avoid[features]=tollRoad`

https://developer.here.com/documentation/routing-api/dev_guide/topics/use-cases/avoid.html
