### ISSUE TITLE
Research: Add new features easily

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#170]
## User story
1. As a NLP component developer
2. I want to have a solution to add new features dynamically
3. So that I can add new features efficiently

## Acceptance criteria
* document solution and communicate it to the rest of the NLP team

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by NebiMucaj** [comment]
_sample query:_ Suche mir eine Route von Berlin nach Paris mit charging stations

_query_object:_ 
{
	...
	charging_stations:true
	...
}

1. Option:
- extend our existing model by new entities  
Steps:
	1. extend the training data by adding new entities in chatette file 
	2. retrain the model
	3. add post-process function 

2. Option:
- implement fuzzy matching
Steps:
        1. detect if a token in the user query matches the target feature(e.g, charging station)
        2. check if the detected feature is negated (e.g., without charging station)
