### ISSUE TITLE
Algorithm for route lengths

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#176]
## User story
1. As a user 
2. I want to search for routes with a minimal or maximal length
3. So that I can plan test drives

## Acceptance criteria
* Draft (e.g. Pseudo code) for implementation is documented in this issue

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by chrisjherm** [comment]
`
request := {MIN_DISTANCE, MAX_DISTANCE}
requestedDistance := {1,2,3,4...}

Route giveMeMyRoute(request, requestedDistance){
        
        // 1km difference in Coordinates
        const ONE_KM_DIFF = 0.015060
        requestDistanceInCoordinates = ONE_KM_DIFF x requestedDistance

        Direction[] capitalDir = {North,East,South,West}
        Coordinates userPos = getCurrentUserCoordinates() // or other defined starting point
        Route[] potentialRoutes

        for(Direction dir: capitalDir){
                // calculates new coordinate from our starting point in the current direction with the given distance
                Coordinate potentialDestination = (tryToFindNewLocationFromHere(userPos, requestDistanceInCoordinates, dir))
                if(hereApi.checkIfRoutingIsPossible(potentialDestination)){
                        Route potentialRoute = hereApi.calculatePotentialRoute(userPos, potentialDestination)
                        potentialRoutes.add(potentialRoute)
                }
        }

        if(request.equals(MIN_DISTANCE)){
                for(Route current: potentialRoutes){
                        if(checkIfDistanceIsAtLeast(current, requestedDistance)){
                                return current
                        }
                }
                return giveMeMyRoute(request, requestedDistance + 1)
        }else if(request.equals(MAX_DISTANCE)){
                for(Route current: potentialRoutes){
                        if(checkIfDistanceIsAtMost(current, requestedDistance)){
                                return current
                        }
                }
                return giveMeMyRoute(request, requestedDistance - 1)
        }else{
                throw Error(unknown request)
        }
}
`

**Comment by chrisjherm** [comment]
Alternative: 
`Direction[] capitalDir = {N,NE,E,SE,S,SW,W,NW}`
