### ISSUE TITLE
Implement route length algorithm

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#178]
## User story
1. As a user 
2. I want to search for routes with a minimal or maximal length
3. So that I can plan test drives

## Acceptance criteria
* route with the minimal/maximal length from the user query is sent to frontend 

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by oliviadargel** [comment]
Follow up ticket to #176

**Comment by chrisjherm** [comment]
CR:
- when one single location from NLP: this is our starting point
- 360 search instead of N,E,S,W
