### ISSUE TITLE
Algorithm for curves

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#179]
## User story
1. As a user 
2. I want to search for routes with a specific number of turns/length of turns
3. So that I can plan test drives

## Acceptance criteria
* Draft (e.g. Pseudo code) for implementation is documented in this issue

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by NumanFidan** [comment]
I will add sources I found here:

* https://roadcurvature.com/how-it-works/ -> This site explains how curve can be calculated, I am not sure if it is implementable though.The method used is explained briefly in the site and also the python project is available at GitHub. 
* https://wiki.openstreetmap.org/wiki/Proposed_features/hazard -> Using hazard tag to find curves in the road. It sounds easier to implement but if the results will be satisfying for our use case, don't know.
* https://gispoint.de/fileadmin/user_upload/paper_gis_open/GI_Forum_2012/537521034.pdf -> This is a paper about adinf curve parameter into calculating routes. I didn't read it thoroughly but it seems to me that it might be helpful for our future implementation
*
