### ISSUE TITLE
API choice documentation

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#192]
## User story
1. As a backend developer
2. I want to document how to change APIs for different query_objects
3. So that it is easier for other developers to make changes

## Acceptance criteria
* Instruction steps are described in wiki
* optional: README also contains the instruction steps

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by chrisjherm** [comment]
I integrated it here:
https://github.com/amosproj/amos2021ws01-geo-data-search/wiki/New-API-addition

But could seperate it if wanted
