### ISSUE TITLE
Show provider of information in detailed view

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#200]
## User story
1. As a user
2. I want to see which provider supplies the information I see
3. So that I can decide whether I like the information the provider supplies or if I have to change the provider for this use case

## Acceptance criteria
* the provider is shown in the detailed view of a result

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by oliviadargel** [comment]
It should be discussed whether the provider info is shown in the detailed view or in the "about" popup. The stakeholders would prefer to have this information in "about", but they leave the decision to us

**Comment by weribell** [comment]
I think it would make a lot more sense to include the API provider info in the detailed view of a specific result (maybe the API could include the provider in a new attribute of a result). IMO it would be more convenient and in case, where results might come from several providers it would be difficult to clearly explain which providers were used for which results in the "about" popup.
