### ISSUE TITLE
Send Data Provider to Frontend

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#207]
## User story
1. As a user
2. I want to see which provider supplies the information I see
3. So that I can decide whether I like the information the provider supplies or if I have to change the provider for this use case

## Acceptance criteria
* the provider is sent to frontend

## Definition of done
* Code was reviewed by another person
* GitHub CI runs successfully
* Feature is merged into main branch

**Comment by chrisjherm** [comment]
Please see branch `backend/provider-to-frontend` for the modified ApiResult-class.

Tasks:

- [X] Send info, when HERE was used

- [ ] Send info, when OSM was used
