### ISSUE TITLE
API capabilities list

### ISSUE THREAD

**Issue by Decappi** [amosproj/amos2021ws01-geo-data-search#22]
## User story
1. As a PO
2. I want to have a list of capabilities for the different APIs we may use
3. So that the team and the stakeholders know the limits and capabilities of the external APIs and can plan the features supported by the app

## Acceptance criteria
* List of acceptable external APIs is created (don't forget about the licences)
* For each external API, a short list of interesting and usable attributes is created
* At least 3 APIs are in the list

**Comment by chrisjherm** [comment]
1/3 API: HERE
Link to issue: https://github.com/amosproj/amos2021ws01-geo-data-search/issues/36
Work in progress

**Comment by chrisjherm** [comment]
2/3 API: OpenStreetMap
Examples: https://wiki.openstreetmap.org/wiki/Frameworks
Variety of possible API/Frameworks

**Comment by Decappi** [comment]
Possible APIs
Geotools
Geoserver

**Comment by oliviadargel** [comment]
Stakeholder only wants HERE API, so this Ticket is deprecated
