### ISSUE TITLE
Documentation in Deliverables

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#252]
Each Team should update their documentation in the GitHub Wiki, see [Deliverables Document](https://docs.google.com/document/d/1GJhwCKf7U3sSZBQjNSu5z1JqssSQTw9Z_3PI4_88v1A/edit#heading=h.v3rr3n206838)
for more information

**Comment by chrisjherm** [comment]
Created subtask for backend:
https://github.com/amosproj/amos2021ws01-geo-data-search/issues/257
