### ISSUE TITLE
Receive input string from frontend

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#41]
## User story
1. As a backend developer
2. I want to receive a Strins from frontend
3. So that I can forward it to the NLP component

## Acceptance criteria
* 

## Definition of done
* Added only after week 5
* The same for all features

**Comment by chrisjherm** [comment]
First dummy simulated with Postman:
Postman POST: `localhost:8080/backend/user_query`
Postman Body/x-www.form-urlencoded:

```
KEY = ttt
VALUE = sss
```

Result: parameter isr eceived in the backend method `FrontendController.receiveQueryFromFrontend( )` and can be printed.
