### ISSUE TITLE
Receive JSON from NLP component

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#43]
## User story
1. As a backend developer
2. I need to receive the JSON from the NLP component
3. So that I can request external APIs with the correct criteria

## Acceptance criteria
* all JSON nodes are read and stored

## Definition of done
* Added only after week 5
* The same for all features

**Comment by chrisjherm** [comment]
First dummy simulated with Postman:
Postman POST: localhost:8080/backend/create
Postman Body/raw/JSON:
{
    "what": "waaas?",
    "where": "woooo?",
    "spec": "nix"
}

Resultat: alle drei Parameter werden in der Backend-Methode FrontendController.receiveNlpAnswer( ) empfangen und lassen sich auslesen.

**Comment by chrisjherm** [comment]
changed to:

First dummy simulated with Postman:
Postman POST: `localhost:8080/backend/nlp_answer`
Postman Body/raw/JSON:

```
{
    "what": "waaas?",
    "where": "woooo?",
    "spec": "nix"
}
```

Result: all three parameters are received in the backend method `FrontendController.receiveNlpAnswer( )` and can be printed.
