### ISSUE TITLE
Research best practices for NLP component

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#51]
## User story
1. As a NLP component developer
2. I need to research best practices for NLP
3. So that I can implement a durable state of the art system

## Acceptance criteria
* Facts for different pre(processing) steps in NLP
* Evaluation of them

## Definition of done
* Added only after week 5
* The same for all features

**Comment by NebiMucaj** [comment]
**Goal:**: Extract pre-defined information from user queries and provide a data structure that can be consumed by the search service.
![NER](https://user-images.githubusercontent.com/50967114/141370710-c03dea53-320f-47b1-8464-e813821dfb83.png)
**Approach**: Use Named Entity Recognition (NER) to identify the important information

**NER**
Named Entity Recognition is the task of recognizing an entity/class in texts, for example, recognizing Berlin as a location. 
The library spaCy in Python provides a Named Entity Recogniser which enables training a model with custom labels.
For our purpose, we can use the NER to identify entities from a user query, like location, query object, or height: 

![custom_label](https://user-images.githubusercontent.com/50967114/141378400-9c7622c8-3e76-41e8-b151-60cdda63a95e.png)

**Requirements**: We need a training data set to fit the model. Therefore we need user queries in a certain format. One format is the BILUO tagging scheme that assigns a specific tag to each token:

**B**egin = The first token of a multi-token entity
**I**N = An inner token of a multi-token entity
**L**ast = The final token a multi-token entity
**U**nit = A single-token entity
**O**ut = A non-entity token

_A sample record of the training data set:_ 
Finde        =>       **O**
alle          =>        **O** 
Berge      =>        **U**
in           =>          **O**
Berlin     =>          **U**
mit         =>          **O**
einer     =>           **O**
Höhe      =>         **U**
von            =>     **O**
mindestens   => **B**
100              =>    **I**
Meter               =>**F**
