### ISSUE TITLE
Evaluate OpenStreetMap

### ISSUE THREAD

**Issue by oliviadargel** [amosproj/amos2021ws01-geo-data-search#75]
Was kann die API
Passt die Lizenz
Passen die Anforderungen

## User story
1. As a PO
2. I want to have a list of capabilities for the Openstreetmap API
3. So that the team and the stakeholders know the limits and capabilities of Openstreetmap and can plan the features supported by the app

## Acceptance criteria
* A short list of interesting and usable attributes is created

**Comment by chrisjherm** [comment]
To be able to use OSM, you first have to register, which I have done.

OSM is accessible via Overpass API which uses specialized "Wizard Queries" what seems to be a query-language. This would mean additional effort.

I could find a Java-Project on GitHub "osmapi" which could help us using Overpass API in Java but it still requires to learn the wizard query language: https://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide

Also this video may be helpful: https://www.youtube.com/watch?v=q9QI4AfwHoM&t=1186s

OSM with Overpass API is pretty powerful but however, I was still unable to find topographical features like rivers, mountains, hills, valleys.

At this point, I would suggest, that OSM is a little bit more powerful than HERE, but needs more effort to get familiar with. Also there is a lot of documentation and frameworks which I did not managed to overview.

Frameworks: https://wiki.openstreetmap.org/wiki/Frameworks
General: https://wiki.openstreetmap.org/wiki/Overpass_API

License: OSM/Overpass in read-only mode is free to use and there should be no problem regarding our open source project.
