### ISSUE TITLE
Add developer mode to frontend

### ISSUE THREAD

**Issue by weribell** [amosproj/amos2021ws01-geo-data-search#93]
Add optional developer mode with a detailed error trace for improved debugging during development. The mode can be enabled  using an environment variable.

## User story
1. As a developer
2. I want to see error traces
3. So that I can quickly assess the health of the system

## Acceptance criteria
* error traces are shown in the backend if the evironment variable is set
* error traces come from backend if something's broken

**Comment by Decappi** [comment]
ENVIRONMENT=development in docker-compose.yml
